// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/achepkin/banklite/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// AccountService is an autogenerated mock type for the AccountService type
type AccountService struct {
	mock.Mock
}

type AccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountService) EXPECT() *AccountService_Expecter {
	return &AccountService_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: ctx, account
func (_m *AccountService) CreateAccount(ctx context.Context, account *entity.Account) error {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Account) error); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AccountService_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type AccountService_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - account *entity.Account
func (_e *AccountService_Expecter) CreateAccount(ctx interface{}, account interface{}) *AccountService_CreateAccount_Call {
	return &AccountService_CreateAccount_Call{Call: _e.mock.On("CreateAccount", ctx, account)}
}

func (_c *AccountService_CreateAccount_Call) Run(run func(ctx context.Context, account *entity.Account)) *AccountService_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Account))
	})
	return _c
}

func (_c *AccountService_CreateAccount_Call) Return(_a0 error) *AccountService_CreateAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AccountService_CreateAccount_Call) RunAndReturn(run func(context.Context, *entity.Account) error) *AccountService_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function with given fields: ctx, id
func (_m *AccountService) GetAccount(ctx context.Context, id string) (*entity.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountService_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type AccountService_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AccountService_Expecter) GetAccount(ctx interface{}, id interface{}) *AccountService_GetAccount_Call {
	return &AccountService_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, id)}
}

func (_c *AccountService_GetAccount_Call) Run(run func(ctx context.Context, id string)) *AccountService_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AccountService_GetAccount_Call) Return(_a0 *entity.Account, _a1 error) *AccountService_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountService_GetAccount_Call) RunAndReturn(run func(context.Context, string) (*entity.Account, error)) *AccountService_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function with given fields: ctx
func (_m *AccountService) ListAccounts(ctx context.Context) ([]*entity.Account, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 []*entity.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Account, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Account); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountService_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type AccountService_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AccountService_Expecter) ListAccounts(ctx interface{}) *AccountService_ListAccounts_Call {
	return &AccountService_ListAccounts_Call{Call: _e.mock.On("ListAccounts", ctx)}
}

func (_c *AccountService_ListAccounts_Call) Run(run func(ctx context.Context)) *AccountService_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AccountService_ListAccounts_Call) Return(_a0 []*entity.Account, _a1 error) *AccountService_ListAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountService_ListAccounts_Call) RunAndReturn(run func(context.Context) ([]*entity.Account, error)) *AccountService_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountService creates a new instance of AccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountService {
	mock := &AccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
